---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: ConfigMap
        name: bitwarden-ca-bundle
        key: ca.crt
        namespace: external-secrets
      organizationID: 6360593d-a292-4f2f-a6aa-b35300171271
      projectID: c1f9161b-f7ed-405a-a56a-b35300190740
