---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  CLUSTER_NAME: "scr1-cluster-0"
  CLUSTER_ID: "1"
  CONTROL_PLANE_ENDPOINT: "cluster-0.scr1.rabbito.tech"
  INGRESS_ENDPOINT_HOSTNAME: "cluster-0-ie.scr1.rabbito.tech"
  CLUSTER_POD_CIDR: "10.244.0.0/16"
  CLUSTER_SERVICE_CIDR: 10.96.0.0/12
  NATIVE_CIDR: "192.168.8.0/24"
  OSD_HOSTNAME_1: "worker-01"
  OSD_HOSTNAME_2: "worker-02"
  OSD_HOSTNAME_3: "worker-03"
  NAS_1_ADDRESS: "nas-1.scr1.rabbito.tech"
  INT_DOMAIN: "scr1.rabbito.tech"
  GENERIC_CLUSTER_INGRESS: "cluster-0.scr1.rabbito.tech"
  SVC_MQTT_ADDR: 10.45.0.1
  SVC_PLEX_ADDR: 10.45.0.2
  SVC_SYSLOG_ADDR: 10.45.0.5
  SVC_QBITTORRENT_ADDR: 10.45.0.3
  VPN_GATEWAY_VPN_PORT: "51820"
  VPN_FORWARDED_PORT_1: "56220"
  VPN_COUNTRY: US
