---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: "192.168.8.20"
    tailscale.com/proxy-class: default
  name: worker-1
spec:
  externalName: unused
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: "192.168.8.62"
    tailscale.com/proxy-class: default
  name: worker-2
spec:
  externalName: unused
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: "192.168.8.61"
    tailscale.com/proxy-class: default
  name: worker-3
spec:
  externalName: unused
  type: ExternalName
