---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: amd-gpu-operator-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://rocm.github.io/gpu-operator
  timeout: 3m
