---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://perfectra1n.github.io/volsync/charts
  timeout: 3m
