---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  timeout: 3m
  url: oci://registry-1.docker.io/bitnamicharts
