---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://apache.github.io/couchdb-helm
  timeout: 3m
