---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: galoymoney
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/GaloyMoney/charts/gh-pages
  timeout: 3m
