---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: galoy-anthr76
  namespace: flux-system
spec:
  type: "oci"
  interval: 1h
  timeout: 3m
  url: oci://ghcr.io/anthr76/galoy-charts
