---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery-charts
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry.k8s.io/nfd/charts/node-feature-discovery
  timeout: 3m
  type: oci
