---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stakewise-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.stakewise.io
  timeout: 3m
