---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel
    template:
      engineVersion: v2
      data:
        TUNNEL_TOKEN: |-
          {{ printf "{\"a\":\"%s\",\"t\":\"%s\",\"s\":\"%s\"}" .CLOUDFLARE_ACCOUNT_TAG .CLOUDFLARE_TUNNEL_ID .CLOUDFLARE_TUNNEL_SECRET | b64enc }}
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_TAG
      remoteRef:
        key: cloudflareAccountTag
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: cloudflareTunnelId
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: cloudflareTunnelSecret
