---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.media.svc.cluster.local:8989
    api_key: !env_var SONARR__AUTH__APIKEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
    quality_profiles:
      - name: WEB-2160p
      - name: WEB-1080p
      - name: WEB-480p
        upgrade:
          allowed: true
          until_quality: WEBDL-480p
        qualities:
          - name: WEBDL-480p
          - name: WEBRip-480p
    custom_formats:
      # Unwanted release groups
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-2160p
          - name: WEB-1080p
          - name: WEB-480p
      # HDR Boosts
      - trash_ids:
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p
            score: 1000
      - trash_ids:
          - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
        assign_scores_to:
          - name: WEB-2160p
            score: 100
      # Dolby Atmos Audio
      - trash_ids:
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD ATMOS
        assign_scores_to:
          - name: WEB-2160p
            score: 5000
          - name: WEB-1080p
            score: 5000
      - trash_ids:
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
        assign_scores_to:
          - name: WEB-2160p
            score: 3000
          - name: WEB-1080p
            score: 3000

radarr:
  radarr:
    base_url: http://radarr.media.svc.cluster.local:7878
    api_key: !env_var RADARR__AUTH__APIKEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_profiles:
      - name: SQP-1 (2160p)
    include:
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-2160p-default
      - template: radarr-custom-formats-sqp-1-2160p
    custom_formats:
      # Existing from current config
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 0
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)
      # HDR Boosts
      - trash_ids:
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 1000
      - trash_ids:
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 100
      # Dolby Atmos Audio
      - trash_ids:
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 5000
      - trash_ids:
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 3000
