---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - config-pvc.yaml
configMapGenerator:
  - name: minecraft-survival-patches
    files:
      - paper-patches.json
      - variabletime-patches.json
  - name: minecraft-survival-bluemap-config
    files:
      - core.conf
namespace: infra
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  kustomize.toolkit.fluxcd.io/substitute: "disabled"
