---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium
  namespace: kube-system
spec:
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: "10.45.0.80"
  addresses: # This will be ignored
  - type: IPAddress
    value: 10.45.0.80
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: web-gw
    port: 80
    protocol: HTTP
