---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/external-secrets"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-external-secrets
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  dependsOn:
    - name: networking-cert-manager
  path: "./k8s/base/external-secrets/external-secrets"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-cluster-secret-store
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/external-secrets/cluster-secret-store"
  prune: true
