---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-namespace
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/infra"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-unifi
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/infra/unifi"
  prune: true
