---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/kube-system"
  prune: true
# TODO: Re-enable after rubber stamp is deployed
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: kube-system-metrics-server
#   namespace: flux-system
#   labels:
#     component.kutara.io/part-of: definitions
# spec:
#   path: "./k8s/base/kube-system/metrics-server"
#   prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/kube-system/cilium"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium-bgp-config
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  dependsOn:
    - name: kube-system-cilium
  path: "./k8s/base/kube-system/cilium/bgp-config"
  prune: true
