---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/networking"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cert-manager
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/networking/cert-manager"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-cert-manager-issuers
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/networking/cert-manager/issuers"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-trust-manager
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  dependsOn:
    - name: networking-cert-manager
  path: "./k8s/base/networking/trust-manager"
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-trust-manager-bitwarden-sdk-certs
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  dependsOn:
    - name: networking-trust-manager
  path: "./k8s/base/networking/trust-manager/bitwarden-sdk-certs"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-external-dns
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/networking/external-dns"
  prune: true
