---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/snapshot-controller"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller-snapshot-controller
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/snapshot-controller/snapshot-controller"
  prune: true
