---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-system
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/volsync-system"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-system-volsync
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/volsync-system/volsync"
  prune: true
