---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 9m0s
  ref:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    tag: v0.31.4
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux
  images:
    - name: fluxcd/helm-controller
      newName: ghcr.io/fluxcd/helm-controller
    - name: fluxcd/image-automation-controller
      newName: ghcr.io/fluxcd/image-automation-controller
    - name: fluxcd/image-reflector-controller
      newName: ghcr.io/fluxcd/image-reflector-controller
    - name: fluxcd/kustomize-controller
      newName: ghcr.io/fluxcd/kustomize-controller
    - name: fluxcd/notification-controller
      newName: ghcr.io/fluxcd/notification-controller
    - name: fluxcd/source-controller
      newName: ghcr.io/fluxcd/source-controller
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            spec:
              containers:
                - name: manager
                  resources:
                    requests:
                      cpu: 500m
                      memory: 128Mi
                    limits:
                      cpu: "2"
                      memory: 2048Mi
      target:
        kind: Deployment
        labelSelector: control-plane=controller
