---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium-gateway-api-crds
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/kube-system/cilium/gateway-api/crds"
  prune: true
