---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-cluster-qgr1
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  path: "./k8s/base/tenant-cluster-qgr1"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-cluster-qgr1-control-plane
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  dependsOn:
    - name: kamaji-system-kamaji
  path: "./k8s/base/tenant-cluster-qgr1/control-plane"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-cluster-qgr1-boostrao
  namespace: flux-system
  labels:
    component.kutara.io/part-of: definitions
spec:
  dependsOn:
    - name: kamaji-system-kamaji
  path: "./k8s/base/tenant-cluster-qgr1/bootstrap"
  prune: true
