---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: vega11-gpu
  namespace: node-feature-discovery
spec:
  rules:
    - name: "vega11-gpu"
      labels:
        "feature.node.kubernetes.io/custom-vega11-gpu": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: {op: In, value: ["0300"]}
            vendor: {op: In, value: ["1002"]}
            device: {op: In, value: ["15dd"]}
