---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zigbee-usb
  namespace: node-feature-discovery
spec:
  rules:
    - name: "zigbee"
      labels:
        "feature.node.kubernetes.io/custom-zigbee": "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: {op: In, value: ["ff"]}
            vendor: {op: In, value: ["1a86"]}
            device: {op: In, value: ["7523"]}
