---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-10g-nic
  namespace: node-feature-discovery
spec:
  rules:
    - name: "intel-10g"
      labels:
        "feature.node.kubernetes.io/custom-intel-10g": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: {op: In, value: ["0200"]}
            vendor: {op: In, value: ["8086"]}
            device: {op: In, value: ["10fb"]}
