---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crd-source
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/traefik/traefik-helm-chart.git
  ref:
    semver: ">=9.19.2 <9.20.0"
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/traefik/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-crd
  namespace: flux-system
spec:
  interval: 5m
  prune: false
  sourceRef:
    kind: GitRepository
    name: traefik-crd-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: ingressroutes.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: ingressroutetcps.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: ingressrouteudps.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: ingressrouteudps.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: middlewares.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: serverstransports.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: tlsoptions.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: tlsstores.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      name: traefikservices.traefik.containo.us
  timeout: 2m
