---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: networking
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.2.1
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 3
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.2.1
    config:
      existingSecret: oauth2-proxy
      configFile: |-
        email_domains = [ '*' ]
        upstreams = [ "static://200" ]
        silence_ping_logging = true
    extraArgs:
      cookie-domain: kutara.io
      cookie-secure: true
      oidc-groups-claim: https://kutara.io/groups
      oidc-issuer-url: https://kutara-dev.us.auth0.com/
      pass-authorization-header: true
      pass-user-headers: true
    # code-challenge-method: S256
      prefer-email-to-user: true
      provider: oidc
      set-authorization-header: true
      set-xauthrequest: true
      skip-provider-button: null
      whitelist-domain: .kutara.io
      reverse-proxy: true
    ingress:
      enabled: true
      className: nginx
      path: /oauth2
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - auth.kutara.io
      tls:
        - hosts:
            - auth.kutara.io
          secretName: oauth2-tls
