---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal-rabbito
  namespace: networking
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
  values:
    interval: 5m
    # logLevel: debug
    serviceMonitor:
      enabled: true
    provider:
      name: rfc2136
    triggerLoopOnEvent: true
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: tsig
    policy: sync
    txtPrefix: "${CLUSTER_NAME}."
    sources:
      - gateway-httproute
      - gateway-tlsroute
      - gateway-tcproute
      - gateway-udproute
      - service
    extraArgs:
      - --rfc2136-host=10.20.99.1
      - --rfc2136-port=53
      - --rfc2136-zone=qgr1.rabbito.tech
      - --rfc2136-tsig-keyname=dhcp-update-key
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-axfr
      - --gateway-name=cilium-internal
      - --gateway-namespace=kube-system
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        cpu: 40m
        memory: 245M
