---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - secret.sops.yaml
configMapGenerator:
  - name: minecraft-luckperms-template
    files:
      - config.yml=luckperms-config.yml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  kustomize.toolkit.fluxcd.io/substitute: "disabled"
