---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls
  namespace: infra
spec:
  secretName: "unifi-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "unifi.qgr1.rabbito.tech"
