---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: unifi-kopia
  namespace: infra
spec:
  sourcePVC: unifi-data
  trigger:
    schedule: "0 * * * *"
  kopia:
    copyMethod: Snapshot
    repository: volsync-kopia
    parallelism: 2
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    cacheStorageClassName: fast-ceph-block
    compression: zstd-fastest
    retain:
      hourly: 24
      daily: 7
      weekly: 4
