---
collections:
  - name: kubernetes.core
  - name: ansible.posix
    version: "1.4.0"
  - name: community.general
  - name: community.sops
  - name: vyos.vyos
  - name: containers.podman
    version: "1.9.4"
  - name: community.routeros
    version: "2.2.1"
roles:
  - src: git@github.com:anthr76/routeros-configure.git
    scm: git
    name: anthr76.routeros-configure
    version: main
  - src: https://github.com/mrlesmithjr/ansible-zfs.git
    scm: git
    name: mrlesmithjr.zfs
    version: b80e84d6938eb7730faeffc7ff7d8aa06ad5bef7
  - src: https://github.com/bjw-s/ansible-role-vyos
    version: v0.2.0
