---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-nfs-media-lb
  namespace: rook-ceph
  annotations:
    lbipam.cilium.io/ips: 10.45.0.30
    external-dns.alpha.kubernetes.io/hostname: nfs.qgr1.rabbito.tech
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
  selector:
    app: rook-ceph-nfs
    ceph_nfs: media-nfs
    instance: a
