name: nyc1-flux-update-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  flux-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Update Flux components
        id: update
        run: |
          UGLY_VERSION="$(flux -v)"
          VERSION="v${UGLY_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --network-policy=false \
            --export > ./clusters/nyc1/gotk/flux-system/gotk-components.yaml
          echo "::set-output name=flux_version::$VERSION"
      - name: Create pull request for Flux update
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.NWK1_FLUX_PAT }}
          branch: "flux/update-${{ steps.update.outputs.flux_version }}"
          delete-branch: true
          title: "update flux components to ${{ steps.update.outputs.flux_version }}"
          signoff: true
          committer: "Anthony Rabbito <hello@anthonyrabbito.com>"
          author: "Anthony Rabbito <hello@anthonyrabbito.com>"
          assignees: "anthr76"
          commit-message: "update flux components to ${{ steps.update.outputs.flux_version }}"
          body: |
            Signed-off-by: Anthony Rabbito <hello@anthonyrabbito.com>
          labels: flux/update
